/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maniburgerFinanceiro2_0;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import maniClass.Ingredientes;
import model.dao.IngredientesDAO;
import model.dao.LancheDAO;
import model.dao.Lanche_IngredienteDAO;

/**
 *
 * @author lanna
 */
public class entradaNoite extends javax.swing.JPanel {

    /**
     * Creates new form entradaNoite
     */
    public entradaNoite() {
        initComponents();

        
    }
    
    
        public void readJTable() {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        IngredientesDAO idao = new IngredientesDAO(); 
        Lanche_IngredienteDAO lidao= new Lanche_IngredienteDAO();
        for (Ingredientes i: idao.read()){
            i.setVendidos(lidao.readNumVendas(diaMes.getText(), i.getCod()));
            Double valorTotal= i.getVendidos()*i.getPreVendaPorcao();
            modelo.addRow(new Object []{
                i.getNome(),
                i.getCod(),
                i.getPreVendaPorcao(),
                i.getVendidos(),
                valorTotal
                
                
                
            });
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        entradaTotalCartao = new javax.swing.JTextField();
        entradaTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        emtradaTotalDinheiro = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        diaMes = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel2.setText("ENTRADA TOTAL:");

        jLabel3.setText("ENTRADA NO CARTÃO:");

        entradaTotalCartao.setEditable(false);
        entradaTotalCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaTotalCartaoActionPerformed(evt);
            }
        });

        entradaTotal.setEditable(false);
        entradaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaTotalActionPerformed(evt);
            }
        });

        jLabel1.setText("ENTRADA NO DINHEIRO:");

        emtradaTotalDinheiro.setEditable(false);
        emtradaTotalDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emtradaTotalDinheiroActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "INGREDIENTE", "CODIGO DO INGREDIENTE", "PREÇO DA UNIDADE", "QUANTIDADE VENDIDA", "VALOR TOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel4.setText("DIA/MES: ");

        diaMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaMesActionPerformed(evt);
            }
        });

        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(entradaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(diaMes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                    .addComponent(jButton1)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(entradaTotalCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(emtradaTotalDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 157, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(diaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(entradaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(entradaTotalCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(emtradaTotalDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void entradaTotalCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaTotalCartaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaTotalCartaoActionPerformed

    private void diaMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaMesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Double totalNoite=0.00;
        Double totalCartao = 0.00;
        Double totalDinheiro = 0.00;
        LancheDAO l = new LancheDAO();
        try {
            totalNoite=l.readEntrada(diaMes.getText());
            totalCartao = l.readEntradaCartao(diaMes.getText());
            totalDinheiro=l.readEntradaDinheiro(diaMes.getText());
        } catch (SQLException ex) {
            Logger.getLogger(entradaNoite.class.getName()).log(Level.SEVERE, null, ex);
        }
        entradaTotal.setText(Double.toString(totalNoite));
        entradaTotalCartao.setText(Double.toString(totalCartao));
        emtradaTotalDinheiro.setText(Double.toString(totalDinheiro));
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        jTable1.setRowSorter(new TableRowSorter(modelo));
        readJTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void entradaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaTotalActionPerformed

    private void emtradaTotalDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emtradaTotalDinheiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emtradaTotalDinheiroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField diaMes;
    private javax.swing.JTextField emtradaTotalDinheiro;
    private javax.swing.JTextField entradaTotal;
    private javax.swing.JTextField entradaTotalCartao;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
