/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maniburger2_0;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import maniClass.Lanche;
import maniClass.Pedidos;
import maniClass.tradutor2_0;
import model.dao.IngredientesDAO;

/**
 *
 * @author lanna
 */
public class addLanche extends javax.swing.JPanel {

    private ArrayList<String> ingredientes;
    private String[] Ing;
    private String lanche;
    public Pedidos pedido;
    private Lanche l;
    tradutor2_0 t;

    /**
     * Creates new form Lanche
     */
    public addLanche(Lanche l) {
        initComponents();
        this.l = l;
        t = new tradutor2_0();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formaPagamento = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtDonoLanche = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoLanche = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLanche = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTaxaEntrega = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTaxaExtra = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtValorTaxaExtra = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();

        jLabel1.setText("DONO DO LANCHE:");

        txtDonoLanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonoLancheActionPerformed(evt);
            }
        });

        jLabel2.setText("CODIGO DO LANCHE:");

        txtCodigoLanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoLancheActionPerformed(evt);
            }
        });

        txtLanche.setColumns(20);
        txtLanche.setRows(5);
        jScrollPane1.setViewportView(txtLanche);

        jLabel3.setText("RESUMO DO LANCHE:");

        jButton1.setText("IMPRIMIR PARA CHAPA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CONFIRMAR LANCHE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("FORMA DE PAGAMENTO:");

        jButton3.setText("ENVIAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setText("TROCO PARA:");

        jTextField3.setText("0");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel6.setText("TAXA DE ENTREGA:");

        txtTaxaEntrega.setText("0");

        jLabel8.setText("NOME DA TAXA:");

        txtTaxaExtra.setText("TAXA EXTRA");
        txtTaxaExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTaxaExtraActionPerformed(evt);
            }
        });

        jLabel9.setText("TAXA:");

        txtValorTaxaExtra.setText("0");

        formaPagamento.add(jRadioButton1);
        jRadioButton1.setText("Cartão");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        formaPagamento.add(jRadioButton2);
        jRadioButton2.setText("Dinheiro");

        jButton4.setText("IMPRIMIR MONTAGEM");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDonoLanche, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel3)))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtCodigoLanche, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTaxaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTaxaExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtValorTaxaExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jRadioButton2)
                                .addComponent(jRadioButton1)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDonoLanche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigoLanche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTaxaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTaxaExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorTaxaExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButton3)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jLabel5)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        l.setDonoLanche(txtDonoLanche.getText());
        l.setIngredientes(t.listaIng(txtCodigoLanche.getText()));
        l.setTaxaEntrega(Double.parseDouble(txtTaxaEntrega.getText()));
        l.setTaxaExtra(txtTaxaExtra.getText());
        l.setValorTaxaExtra(Double.parseDouble(txtValorTaxaExtra.getText()));
        l.setPreco(t.calculaPreco(l));
        if (jRadioButton1.isSelected()) {
            l.setFormaPg(1);
        } else if (jRadioButton2.isSelected()) {
            l.setFormaPg(2);
            l.setTroco(t.calculaTroco(Double.parseDouble(jTextField3.getText()), l));
        } else {
            JOptionPane.showMessageDialog(null, "Selecione a forma de pagamento ");
        }
        txtLanche.setText(t.txtResumo(l));
        //MANDAR IMPRIMIR A STRING ABAIXO

        jButton3.setBackground(Color.yellow);
        //txtLanche.setText(tradutor(jTFCodigo.getText()));

    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtTaxaExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTaxaExtraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTaxaExtraActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        l.setDonoLanche(txtDonoLanche.getText());
        l.setIngredientes(t.listaIng(txtCodigoLanche.getText()));
        l.setTaxaEntrega(Double.parseDouble(txtTaxaEntrega.getText()));
        l.setTaxaExtra(txtTaxaExtra.getText());
        l.setValorTaxaExtra(Double.parseDouble(txtValorTaxaExtra.getText()));
        l.setPreco(t.calculaPreco(l));
        //MANDAR IMPRIMIR A STRING ABAIXO
        t.impressora(t.txtMontagem(l));
        jButton1.setBackground(Color.yellow);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        l.setDonoLanche(txtDonoLanche.getText());
        l.setIngredientes(t.listaIng(txtCodigoLanche.getText()));
        l.setTaxaEntrega(Double.parseDouble(txtTaxaEntrega.getText()));
        l.setTaxaExtra(txtTaxaExtra.getText());
        l.setValorTaxaExtra(Double.parseDouble(txtValorTaxaExtra.getText()));
        l.setPreco(t.calculaPreco(l));
        if (jRadioButton1.isSelected() ||jRadioButton2.isSelected()){
        if (jRadioButton1.isSelected()) {
            l.setFormaPg(1);
        } else if (jRadioButton2.isSelected()) {
            l.setFormaPg(2);
            l.setTroco(t.calculaTroco(Double.parseDouble(jTextField3.getText()), l));
        }
        jButton2.setBackground(Color.yellow);
        txtLanche.setText(t.txtCompleto(l));
        t.impressora(t.txtCompleto(l));
        }else{
            JOptionPane.showMessageDialog(null, "Selecione a forma de pagamento ");
        }
        //MANDAR IMPRIMIR A STRING ABAIXO

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtCodigoLancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoLancheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoLancheActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void txtDonoLancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonoLancheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonoLancheActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        l.setDonoLanche(txtDonoLanche.getText());
        l.setIngredientes(t.listaIng(txtCodigoLanche.getText()));
        l.setTaxaEntrega(Double.parseDouble(txtTaxaEntrega.getText()));
        l.setTaxaExtra(txtTaxaExtra.getText());
        l.setValorTaxaExtra(Double.parseDouble(txtValorTaxaExtra.getText()));
        l.setPreco(t.calculaPreco(l));
        t.impressora(t.txtMontagem(l));
        //MANDAR IMPRIMIR A STRING ABAIXO

        jButton4.setBackground(Color.yellow);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup formaPagamento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField txtCodigoLanche;
    public javax.swing.JTextField txtDonoLanche;
    private javax.swing.JTextArea txtLanche;
    private javax.swing.JTextField txtTaxaEntrega;
    private javax.swing.JTextField txtTaxaExtra;
    private javax.swing.JTextField txtValorTaxaExtra;
    // End of variables declaration//GEN-END:variables
}
