/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maniburger2_0;

import java.awt.Color;
import static java.awt.Color.yellow;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import maniClass.ButtonTabComponent;
import maniClass.Ingredientes;
import maniClass.Lanche;
import maniClass.Pedidos;
import model.dao.IngredientesDAO;
import model.dao.LancheDAO;
import model.dao.Lanche_IngredienteDAO;
import model.dao.PedidosDAO;

/**
 *
 * @author lanna
 */
public class addPedidos extends javax.swing.JPanel {
    
    Pedidos pedido;
    int numLanches;
    Lanche lan;
    Date d;
    int numPedido;
    int numPedidosDaNoite;

    /**
     * Creates new form Pedidos
     */
    public addPedidos(int i) {
        numPedidosDaNoite=i;
        initComponents();
        pedido = new Pedidos(txtNomePedido.getText());
        numLanches = 0;
        pedido.setHorario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNomePedido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        panePedidos = new javax.swing.JTabbedPane();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jLabel1.setText("NOME DO DONO DO PEDIDO:");

        txtNomePedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomePedidoActionPerformed(evt);
            }
        });

        jLabel2.setText("ENDEREÇO:");

        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });

        jButton1.setText("CONFIRMAR PEDIDO");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        panePedidos.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                panePedidosAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jButton2.setText("CANCELAR PEDIDO");

        jButton3.setText("ADICIONAR LANCHE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("ENVIAR ENDEREÇO");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panePedidos)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNomePedido, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtNomePedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panePedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomePedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomePedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomePedidoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String nome = null;
        if (nome == null || nome.equals("")) {
            nome = JOptionPane.showInputDialog("Qual o nome do Dono do Lanche?");
            if (nome != null || nome.equals("")) {
                numLanches++;
                nome += " " + numLanches;
                pedido.setNomeCliente(txtNomePedido.getText() + " " + Integer.toString(numLanches));
                lan = new Lanche(nome, numLanches, pedido.getNomeCliente(),numPedidosDaNoite);
                pedido.addLanche(lan);
                addLanche l = new addLanche(lan);
                l.setName(nome);
                l.txtDonoLanche.setText(nome);

                panePedidos.add(l);
                panePedidos.setSelectedComponent(l);

                int j = panePedidos.getSelectedIndex();
                panePedidos.setTabComponentAt(j, new ButtonTabComponent(panePedidos));

                l.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        // TODO add your handling code here:
        //criar as DAO's, insere pedidos, lanche, e ingredientes
        PedidosDAO pDAO = new PedidosDAO();
        LancheDAO lDAO = new LancheDAO();
        Lanche_IngredienteDAO liDAO = new Lanche_IngredienteDAO();
        int i, j;
        pedido.setRota(criaRota());
        
if( !jButton1.getBackground().equals(Color.YELLOW)){
        pDAO.create(pedido);
      pedido.setCodPedido(pDAO.readMaxCod());

        for (i = 0; i < pedido.getLanches().size(); i++) {
            lDAO.create(pedido.getLanches().get(i), pedido.getCodPedido());
            for (j = 0; j < pedido.getLanches().get(i).getIngredientes().size(); j++) {
                liDAO.create(pedido.getLanches().get(i), pedido.getLanches().get(i).getIngredientes().get(j), pedido.getCodPedido());
            }
        }
        jButton1.setBackground(Color.YELLOW);
        
}else{
        //caso ja tenha enviado uma vez, edita o pedido, apaga os lanches e cria dnv
            JOptionPane.showMessageDialog(null, "Pedido: "+pedido.getCodPedido());
       pDAO.update(pedido, pedido.getCodPedido());
       lDAO.delete(pedido.getCodPedido());
       liDAO.delete(pedido.getCodPedido());
       System.out.println(pedido.getEndereco());
        for (i = 0; i < pedido.getLanches().size(); i++) {
            lDAO.create(pedido.getLanches().get(i), pedido.getCodPedido());
            for (j = 0; j < pedido.getLanches().get(i).getIngredientes().size(); j++) {
                liDAO.create(pedido.getLanches().get(i), pedido.getLanches().get(i).getIngredientes().get(j), pedido.getCodPedido());
            }
        }
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        jButton1.setBackground(Color.YELLOW);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        pedido.setEndereco(txtEndereco.getText());
        jButton4.setBackground(yellow);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void panePedidosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_panePedidosAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_panePedidosAncestorAdded

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTabbedPane panePedidos;
    private javax.swing.JTextField txtEndereco;
    public javax.swing.JTextField txtNomePedido;
    // End of variables declaration//GEN-END:variables
public boolean verificaIgualdade(HashMap<Ingredientes, Integer> map, Ingredientes k) {
        for (Map.Entry<Ingredientes, Integer> x : map.entrySet()) {
            if (x.getKey().getCod() == k.getCod()) {
                return true;
            }
        }
        return false;
    }

    public String criaRota() {
        String rota = "";
        String nomePreco = "";
        double precoTotal = 0;
        double trocoTotal = 0;
        HashMap<String, Integer> map = new HashMap<String, Integer>();

        for (int i = 0; i < pedido.getLanches().size(); i++) {
            precoTotal+=pedido.getLanches().get(i).getPreco();
            trocoTotal+=pedido.getLanches().get(i).getTroco();

            for (int j = 0; j < pedido.getLanches().get(i).getIngredientes().size(); j++) {
                if (pedido.getLanches().get(i).getIngredientes().get(j).getTipo() == 3) {
                    if (map.containsKey(pedido.getLanches().get(i).getIngredientes().get(j).getNome())) {
                        map.put(pedido.getLanches().get(i).getIngredientes().get(j).getNome(), map.get(pedido.getLanches().get(i).getIngredientes().get(j).getNome()) + 1);
                    } else {

                        map.put(pedido.getLanches().get(i).getIngredientes().get(j).getNome(), 1);
                    }
                }
            }
            nomePreco += pedido.getLanches().get(i).getDonoLanche() + "(" + pedido.getLanches().get(i).getFormaPg() + ":" + pedido.getLanches().get(i).getPreco() + "  troco:" + pedido.getLanches().get(i).getTroco() + ")  \n";

        }
        rota+="\n\n\n Cliente: "+pedido.getNomeCliente()+"\n";
        rota += String.valueOf(pedido.getLanches().size()) + "H"; //xH
        for (Map.Entry<String, Integer> x : map.entrySet()) {
            rota += "-" + x.getValue() + x.getKey();                //xH-32refri-34smoot
        }
        rota += "\n Endereco: " + pedido.getEndereco() + "\n " +"  , lanches: \n"+ nomePreco+" \n , precoTOTAL: "+precoTotal+"  , trocoTotal: "+trocoTotal;
       

        System.out.println(rota);
        return rota;
    }

}
